from setuptools import setup
import os
import subprocess

requires = [
    'pyramid',
    'pyramid_chameleon',
    'pyramid_debugtoolbar',
    'numpy',
    'marshmallow',
    'deform',
    'sqlalchemy',
    'pyramid_tm',
    'pillow',
    'bcrypt',
    'waitress',
    'rarfile',
    'libarchive-c',
    'zope.sqlalchemy',
    'mysqlclient',
    'requests'
]

# Fetch version from git tags, and write to version.py.
# Also, when git is not available (PyPi package), use stored version.py.
version_py = os.path.join(os.path.dirname(__file__), 'version.py')

try:
    version_git = subprocess.check_output(["git", "describe"]).decode('utf-8').rstrip()
except:
    with open(version_py, 'r') as fh:
        version_git = open(version_py).read().strip().split('=')[-1].replace('"','')

version_msg = "# Do not edit this file, pipeline versioning is governed by git tags"
with open(version_py, 'w') as fh:
    print(version_msg, os.linesep, "__version__=", version_git)
    fh.write(version_msg + os.linesep + "__version__=" + version_git)


setup(name='titledb',
      version=version_git,
      install_requires=requires,
      entry_points="""\
      [paste.app_factory]
      main = titledb:main
      [console_scripts]
      initialize_titledb_db = titledb.initialize_db:main
      update_titledb_db = titledb.update_db:main
      titledb_cli = titledb.cli:main
      """,
)
